export const ValidationCode = {
	COMPANY_NAME_REQUIRED: 'COMPANY_NAME_REQUIRED',
	COMPANY_NAME_MAX: 'COMPANY_NAME_MAX',
	COMPANY_DOMAIN_REQUIRED: 'COMPANY_DOMAIN_REQUIRED',
	COMPANY_DOMAIN_FORMAT: 'COMPANY_DOMAIN_FORMAT',
	COMPANY_DOMAIN_DUPLICATE: 'COMPANY_DOMAIN_DUPLICATE',
	COMPANY_RATE_REQUIRED: 'COMPANY_RATE_REQUIRED',
	COMPANY_RATE_NUMBER: 'COMPANY_RATE_NUMBER',
	COMPANY_RATE_POSITIVE: 'COMPANY_RATE_POSITIVE',
	COMPANY_BORROWING_CAPACITY_MIN: 'COMPANY_BORROWING_CAPACITY_MIN',
	COMPANY_BORROWING_CAPACITY_MAX: 'COMPANY_BORROWING_CAPACITY_MAX',
	COMPANY_FREQUENCY: 'COMPANY_FREQUENCY',

	COMPANY_TERM_DURATION_REQUIRED: 'COMPANY_TERM_DURATION_REQUIRED',
	COMPANY_TERM_DURATION_INTEGER: 'COMPANY_TERM_DURATION_INTEGER',
	COMPANY_TERM_DURATION_MIN: 'COMPANY_TERM_DURATION_MIN',
	COMPANY_TERM_DURATION_MAX: 'COMPANY_TERM_DURATION_MAX',
	COMPANY_TERM_TYPE_INVALID: 'COMPANY_TERM_TYPE_INVALID',
	COMPANY_TERM_ALREADY_ASSIGNED: 'COMPANY_TERM_ALREADY_ASSIGNED',
	COMPANY_TERM_TYPE_MISMATCH_SALARY_FREQUENCY:
		'COMPANY_TERM_TYPE_MISMATCH_SALARY_FREQUENCY',
	COMPANY_PAYROLL_FREQUENCY_CONFLICTS_WITH_TERMS:
		'COMPANY_PAYROLL_FREQUENCY_CONFLICTS_WITH_TERMS',

	COMPANY_CREATE_INITIAL_TERMS_INVALID: 'COMPANY_CREATE_INITIAL_TERMS_INVALID',

	APPLICATION_TERM_REQUIRED: 'APPLICATION_TERM_REQUIRED',
	APPLICATION_SALARY_FREQUENCY_INVALID: 'APPLICATION_SALARY_FREQUENCY_INVALID',
	APPLICATION_VALUE_REQUIRED: 'APPLICATION_VALUE_REQUIRED',
	APPLICATION_VALUE_POSITIVE: 'APPLICATION_VALUE_POSITIVE',
	APPLICATION_RFC_LENGTH: 'APPLICATION_RFC_LENGTH',
	APPLICATION_RFC_INVALID: 'APPLICATION_RFC_INVALID',
	APPLICATION_CLABE_LENGTH: 'APPLICATION_CLABE_LENGTH',
	APPLICATION_CLABE_INVALID: 'APPLICATION_CLABE_INVALID',
	APPLICATION_POSTAL_CODE_LENGTH: 'APPLICATION_POSTAL_CODE_LENGTH',
	APPLICATION_INVALID: 'APPLICATION_INVALID',
	DOCUMENT_TYPE_INVALID: 'DOCUMENT_TYPE_INVALID',
	DOCUMENT_STATUS_INVALID: 'DOCUMENT_STATUS_INVALID',
	CUENTA_APPLICATION_EMAIL_DOMAIN: 'CUENTA_APPLICATION_EMAIL_DOMAIN',
	CUENTA_APPLICATION_COMPANY_NO_RATE: 'CUENTA_APPLICATION_COMPANY_NO_RATE',
	CUENTA_APPLICATION_COMPANY_NO_TERMS: 'CUENTA_APPLICATION_COMPANY_NO_TERMS',
	CUENTA_APPLICATION_TERM_NOT_AVAILABLE:
		'CUENTA_APPLICATION_TERM_NOT_AVAILABLE',
	CUENTA_APPLICATION_DUPLICATE_WAIT: 'CUENTA_APPLICATION_DUPLICATE_WAIT',
	CUENTA_APPLICATION_EXISTING_ACTIVE: 'CUENTA_APPLICATION_EXISTING_ACTIVE',
	CUENTA_APPLICATION_NOT_FOUND: 'CUENTA_APPLICATION_NOT_FOUND',
	CUENTA_APPLICATION_AUTHORIZATION_PACKAGE_INCOMPLETE:
		'CUENTA_APPLICATION_AUTHORIZATION_PACKAGE_INCOMPLETE',
	CUENTA_APPLICATION_FILE_REQUIRED: 'CUENTA_APPLICATION_FILE_REQUIRED',
	CUENTA_APPLICATION_FILE_MAX_SIZE: 'CUENTA_APPLICATION_FILE_MAX_SIZE',
	FILE_TYPE_UNKNOWN: 'FILE_TYPE_UNKNOWN',
	FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
	APPLICATIONS_DOCUMENT_INVALID: 'APPLICATIONS_DOCUMENT_INVALID',
	APPLICATIONS_DOCUMENT_REJECTION_REASON_REQUIRED:
		'APPLICATIONS_DOCUMENT_REJECTION_REASON_REQUIRED',
	APPLICATIONS_DOCUMENT_DECISIONS_REQUIRED:
		'APPLICATIONS_DOCUMENT_DECISIONS_REQUIRED',
	APPLICATIONS_DOCUMENT_REVIEW_FORBIDDEN:
		'APPLICATIONS_DOCUMENT_REVIEW_FORBIDDEN',

	AUTH_EMAIL_NAME_REQUIRED: 'AUTH_EMAIL_NAME_REQUIRED',
	AUTH_EMAIL_REQUIRED: 'AUTH_EMAIL_REQUIRED',
	AUTH_SIGNUP_EMAIL_NOT_ELIGIBLE: 'AUTH_SIGNUP_EMAIL_NOT_ELIGIBLE',
	AUTH_LOGIN_NO_CREDIT_ACCESS: 'AUTH_LOGIN_NO_CREDIT_ACCESS',
	AUTH_RATE_LIMIT_EXCEEDED: 'AUTH_RATE_LIMIT_EXCEEDED',
	AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
	AUTH_OTP_RESENT_SUCCESS: 'AUTH_OTP_RESENT_SUCCESS',
	AUTH_NOT_AUTHENTICATED: 'AUTH_NOT_AUTHENTICATED',
	AUTH_EMAIL_CHANGE_SAME: 'AUTH_EMAIL_CHANGE_SAME',
	AUTH_EMAIL_ALREADY_REGISTERED: 'AUTH_EMAIL_ALREADY_REGISTERED',
	AUTH_CURRENT_USER_NOT_FOUND: 'AUTH_CURRENT_USER_NOT_FOUND',
	AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
	AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',

	APPLICATIONS_ERROR_GENERIC: 'APPLICATIONS_ERROR_GENERIC',
	APPLICATIONS_REASON_REQUIRED: 'APPLICATIONS_REASON_REQUIRED',
	APPLICATIONS_NOT_FOUND: 'APPLICATIONS_NOT_FOUND',
	APPLICATIONS_ERROR_TRANSITION: 'APPLICATIONS_ERROR_TRANSITION',
	APPLICATIONS_FINANCIAL_TERMS_REQUIRED:
		'APPLICATIONS_FINANCIAL_TERMS_REQUIRED',
	APPLICATIONS_REQUESTS_CANNOT_PREAUTH_OR_AUTH:
		'APPLICATIONS_REQUESTS_CANNOT_PREAUTH_OR_AUTH',
	APPLICATIONS_PREAUTH_EXCEEDS_CAPACITY:
		'APPLICATIONS_PREAUTH_EXCEEDS_CAPACITY',
	APPLICATIONS_PREAUTH_COMPANY_NO_CAPACITY:
		'APPLICATIONS_PREAUTH_COMPANY_NO_CAPACITY',
	APPLICATIONS_AUTHORIZATION_PACKAGE_NOT_APPROVED:
		'APPLICATIONS_AUTHORIZATION_PACKAGE_NOT_APPROVED',

	HR_FIRST_DISCOUNT_DATE_REQUIRED: 'HR_FIRST_DISCOUNT_DATE_REQUIRED',
	HR_FIRST_DISCOUNT_DATE_INVALID: 'HR_FIRST_DISCOUNT_DATE_INVALID',
	HR_ALREADY_APPROVED: 'HR_ALREADY_APPROVED',

	DISBURSE_TRANSFER_REFERENCE_REQUIRED: 'DISBURSE_TRANSFER_REFERENCE_REQUIRED',
	DISBURSE_RECEIPT_REQUIRED: 'DISBURSE_RECEIPT_REQUIRED',
	DISBURSE_HR_NOT_APPROVED: 'DISBURSE_HR_NOT_APPROVED',

	CREDIT_PAYMENT_NOT_FOUND: 'CREDIT_PAYMENT_NOT_FOUND',
	CREDIT_PAYMENT_ALREADY_CONFIRMED: 'CREDIT_PAYMENT_ALREADY_CONFIRMED',
	CREDIT_PAYMENT_NOT_HR_CONFIRMED: 'CREDIT_PAYMENT_NOT_HR_CONFIRMED',
	CREDIT_PAYMENT_ALREADY_INSTALLMENT_CONFIRMED:
		'CREDIT_PAYMENT_ALREADY_INSTALLMENT_CONFIRMED',
	CREDIT_PAYMENT_CSV_PARSE_ERROR: 'CREDIT_PAYMENT_CSV_PARSE_ERROR',
	CREDIT_PAYMENT_CSV_NO_MATCHES: 'CREDIT_PAYMENT_CSV_NO_MATCHES',
	CREDIT_PAYMENT_BULK_EMPTY: 'CREDIT_PAYMENT_BULK_EMPTY',
	CREDIT_PAYMENT_BULK_SELECTION_NON_CONTIGUOUS:
		'CREDIT_PAYMENT_BULK_SELECTION_NON_CONTIGUOUS',
	CREDIT_PAYMENT_CONFIRM_FORBIDDEN: 'CREDIT_PAYMENT_CONFIRM_FORBIDDEN',
	CREDIT_PAYMENT_INSTALLMENT_PERIOD_NOT_ELIGIBLE:
		'CREDIT_PAYMENT_INSTALLMENT_PERIOD_NOT_ELIGIBLE',

	CREDIT_NOT_FOUND: 'CREDIT_NOT_FOUND',
	CREDIT_DEFAULT_ADMIN_ONLY: 'CREDIT_DEFAULT_ADMIN_ONLY',
	CREDIT_DEFAULT_INVALID_STATUS: 'CREDIT_DEFAULT_INVALID_STATUS',
	CREDIT_DEFAULT_NOT_LONG_OVERDUE: 'CREDIT_DEFAULT_NOT_LONG_OVERDUE',

	CREDIT_DEFAULTED_PAYMENT_ACTION_BLOCKED:
		'CREDIT_DEFAULTED_PAYMENT_ACTION_BLOCKED',
	CREDIT_RESTORE_NOT_DEFAULTED: 'CREDIT_RESTORE_NOT_DEFAULTED',

	CREDIT_LIQUIDATE_EARLY_INVALID_STATUS:
		'CREDIT_LIQUIDATE_EARLY_INVALID_STATUS',
	CREDIT_LIQUIDATE_EARLY_NOTHING_PENDING:
		'CREDIT_LIQUIDATE_EARLY_NOTHING_PENDING',
	CREDIT_LIQUIDATE_EARLY_FORBIDDEN: 'CREDIT_LIQUIDATE_EARLY_FORBIDDEN',
	CREDIT_LIQUIDATE_EARLY_SCHEDULE_MISMATCH:
		'CREDIT_LIQUIDATE_EARLY_SCHEDULE_MISMATCH',
	CREDIT_LIQUIDATE_EARLY_CREDIT_NOT_FOUND:
		'CREDIT_LIQUIDATE_EARLY_CREDIT_NOT_FOUND',
	CREDIT_LIQUIDATE_EARLY_TERMS_MISSING: 'CREDIT_LIQUIDATE_EARLY_TERMS_MISSING',
	CREDIT_LIQUIDATE_EARLY_HR_PENDING: 'CREDIT_LIQUIDATE_EARLY_HR_PENDING',
	CREDIT_LIQUIDATE_EARLY_PAYMENT_NOT_FOUND:
		'CREDIT_LIQUIDATE_EARLY_PAYMENT_NOT_FOUND',
	CREDIT_LIQUIDATE_EARLY_PAYMENT_DEFAULTED:
		'CREDIT_LIQUIDATE_EARLY_PAYMENT_DEFAULTED',
	CREDIT_LIQUIDATE_EARLY_PAYMENT_ALREADY_DONE:
		'CREDIT_LIQUIDATE_EARLY_PAYMENT_ALREADY_DONE',
	CREDIT_LIQUIDATE_EARLY_FAILED: 'CREDIT_LIQUIDATE_EARLY_FAILED',
	CREDIT_ID_INVALID: 'CREDIT_ID_INVALID',
} as const

export type ValidationCode =
	(typeof ValidationCode)[keyof typeof ValidationCode]

const VALIDATION_CODE_VALUE_SET: ReadonlySet<string> = new Set(
	Object.values(ValidationCode),
)

export function isValidationCodeMessage(value: string): boolean {
	return VALIDATION_CODE_VALUE_SET.has(value)
}
