/**
 * Validation and server error codes.
 * Backend (Zod, mutations, error handlers) uses these; frontend maps them to i18n.
 * Do not put translation keys here.
 */
export const ValidationCode = {
	// Company / admin
	COMPANY_NAME_REQUIRED: 'COMPANY_NAME_REQUIRED',
	COMPANY_NAME_MAX: 'COMPANY_NAME_MAX',
	COMPANY_DOMAIN_REQUIRED: 'COMPANY_DOMAIN_REQUIRED',
	COMPANY_DOMAIN_FORMAT: 'COMPANY_DOMAIN_FORMAT',
	COMPANY_DOMAIN_DUPLICATE: 'COMPANY_DOMAIN_DUPLICATE',
	COMPANY_RATE_REQUIRED: 'COMPANY_RATE_REQUIRED',
	COMPANY_RATE_NUMBER: 'COMPANY_RATE_NUMBER',
	COMPANY_RATE_POSITIVE: 'COMPANY_RATE_POSITIVE',
	COMPANY_BORROWING_CAPACITY_MIN: 'COMPANY_BORROWING_CAPACITY_MIN',
	COMPANY_BORROWING_CAPACITY_MAX: 'COMPANY_BORROWING_CAPACITY_MAX',
	COMPANY_FREQUENCY: 'COMPANY_FREQUENCY',

	// Dashboard applications
	APPLICATION_TERM_REQUIRED: 'APPLICATION_TERM_REQUIRED',
	APPLICATION_VALUE_REQUIRED: 'APPLICATION_VALUE_REQUIRED',
	APPLICATION_VALUE_POSITIVE: 'APPLICATION_VALUE_POSITIVE',
	APPLICATION_INVALID: 'APPLICATION_INVALID',
	DOCUMENT_TYPE_INVALID: 'DOCUMENT_TYPE_INVALID',
	DOCUMENT_STATUS_INVALID: 'DOCUMENT_STATUS_INVALID',
	DASHBOARD_APPLICATION_EMAIL_DOMAIN: 'DASHBOARD_APPLICATION_EMAIL_DOMAIN',
	DASHBOARD_APPLICATION_COMPANY_NO_RATE:
		'DASHBOARD_APPLICATION_COMPANY_NO_RATE',
	DASHBOARD_APPLICATION_COMPANY_NO_TERMS:
		'DASHBOARD_APPLICATION_COMPANY_NO_TERMS',
	DASHBOARD_APPLICATION_TERM_NOT_AVAILABLE:
		'DASHBOARD_APPLICATION_TERM_NOT_AVAILABLE',
	DASHBOARD_APPLICATION_DUPLICATE_WAIT: 'DASHBOARD_APPLICATION_DUPLICATE_WAIT',
	DASHBOARD_APPLICATION_EXISTING_ACTIVE:
		'DASHBOARD_APPLICATION_EXISTING_ACTIVE',
	DASHBOARD_APPLICATION_NOT_FOUND: 'DASHBOARD_APPLICATION_NOT_FOUND',
	DASHBOARD_APPLICATION_FILE_REQUIRED: 'DASHBOARD_APPLICATION_FILE_REQUIRED',
	DASHBOARD_APPLICATION_FILE_MAX_SIZE: 'DASHBOARD_APPLICATION_FILE_MAX_SIZE',
	FILE_TYPE_UNKNOWN: 'FILE_TYPE_UNKNOWN',
	FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
	APPLICATIONS_DOCUMENT_INVALID: 'APPLICATIONS_DOCUMENT_INVALID',
	APPLICATIONS_DOCUMENT_REJECTION_REASON_REQUIRED:
		'APPLICATIONS_DOCUMENT_REJECTION_REASON_REQUIRED',

	// Auth (login, signup, email change, OTP)
	AUTH_EMAIL_NAME_REQUIRED: 'AUTH_EMAIL_NAME_REQUIRED',
	AUTH_EMAIL_REQUIRED: 'AUTH_EMAIL_REQUIRED',
	AUTH_SIGNUP_EMAIL_NOT_ELIGIBLE: 'AUTH_SIGNUP_EMAIL_NOT_ELIGIBLE',
	AUTH_LOGIN_NO_CREDIT_ACCESS: 'AUTH_LOGIN_NO_CREDIT_ACCESS',
	AUTH_RATE_LIMIT_EXCEEDED: 'AUTH_RATE_LIMIT_EXCEEDED',
	AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
	AUTH_OTP_RESENT_SUCCESS: 'AUTH_OTP_RESENT_SUCCESS',
	AUTH_NOT_AUTHENTICATED: 'AUTH_NOT_AUTHENTICATED',
	AUTH_EMAIL_CHANGE_SAME: 'AUTH_EMAIL_CHANGE_SAME',
	AUTH_EMAIL_ALREADY_REGISTERED: 'AUTH_EMAIL_ALREADY_REGISTERED',
	AUTH_CURRENT_USER_NOT_FOUND: 'AUTH_CURRENT_USER_NOT_FOUND',
	AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
	AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',

	// App (application status, document actions)
	APPLICATIONS_ERROR_GENERIC: 'APPLICATIONS_ERROR_GENERIC',
	APPLICATIONS_REASON_REQUIRED: 'APPLICATIONS_REASON_REQUIRED',
	APPLICATIONS_NOT_FOUND: 'APPLICATIONS_NOT_FOUND',
	APPLICATIONS_ERROR_TRANSITION: 'APPLICATIONS_ERROR_TRANSITION',
} as const

export type ValidationCode =
	(typeof ValidationCode)[keyof typeof ValidationCode]
