name: Type Check, Lint & Unit Tests

on: [push]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --prefer-frozen-lockfile --ignore-scripts

      - name: Type check
        run: pnpm exec tsc --noEmit

      - name: Lint
        run: pnpm check

      - name: Unit tests
        run: pnpm test:unit
